name: dev new - Create signed git clone and image SBOMs

on: workflow_dispatch

env:
        LOGICAL_APP_NAME: demo-project # The app name all these SBOMs will be assosiated with
        APP_VERSION: 1.0.1 # The app version all these SBOMs will be assosiated with
        # SBOM Author meta data - Optional
        AUTHOR_NAME: Alona Dodukh
        AUTHOR_EMAIL: alonadodukh@tetsemail.com
        AUTHOR_PHONE: 123-123-123-12345
        # SBOM Supplier meta data - Optional
        SUPPLIER_NAME: Scribe-Security 
        SUPPLIER_URL: www.scribesecurity.com 
        SUPPLIER_EMAIL: info@scribesecurity.com
        SUPPLIER_PHONE: 001-001-0011
        SCRIBE_URL: "https://airflow.dev.scribesecurity.com/"
        SCRIBE_LOGIN_URL: "https://scribe-hub-dev.us.auth0.com"
        SCRIBE_AUDIENCE: "api.dev.scribesecurity.com"

jobs:

 build:
    runs-on: ubuntu-latest

    permissions:
        contents: read
        packages: write
        id-token: write

    steps:
        - uses: actions/checkout@v3

        - name: Generate signed SBOM for repo content
          uses: scribe-security/action-bom@master
          with:
                target: 'git:.'
                scribe-enable: true
                product-key: "slsa_attest"
                components: packages,files,dep
                scribe-client-id: ${{ secrets.SCRIBE_DEV_NEW_CLIENT_ID }}
                scribe-client-secret: ${{ secrets.SCRIBE_DEV_NEW_CLIENT_SECRET }}
                format: attest
                scribe-url: ${{ env.SCRIBE_URL }}
                scribe-login-url: ${{ env.SCRIBE_LOGIN_URL }}
                scribe-audience: ${{ env.SCRIBE_AUDIENCE }}
                # app-name: $LOGICAL_APP_NAME
                # app-version: $APP_VERSION
                author-name: $AUTHOR_NAME
                author-email: $AUTHOR_EMAIL
                author-phone: $AUTHOR_PHONE
                supplier-name: $SUPPLIER_NAME
                supplier-url: $SUPPLIER_URL
                supplier-email: $SUPPLIER_EMAIL 
                supplier-phone: $SUPPLIER_PHONE

        - name: Build the Docker image
          # run: docker build . -t ${{ github.repository }}:${{ github.sha }}
          run: |
            docker build -t my-image:latest .


        - name: Generate signed SBOM for docker image
            # Used after a docker image is built
          uses: scribe-security/action-bom@master
          with:
                # target: 'docker:${{ github.repository }}:${{ github.sha }}'
                type: docker
                target: 'my-image:latest'
                scribe-enable: true
                product-key: "slsa_attest"
                scribe-client-id: ${{ secrets.SCRIBE_DEV_NEW_CLIENT_ID }}
                scribe-client-secret: ${{ secrets.SCRIBE_DEV_NEW_CLIENT_SECRET }}
                format: attest
                scribe-url: ${{ env.SCRIBE_URL }}
                scribe-login-url: ${{ env.SCRIBE_LOGIN_URL }}
                scribe-audience: ${{ env.SCRIBE_AUDIENCE }}
                # app-name: $LOGICAL_APP_NAME
                # app-version: $APP_VERSION
                author-name: $AUTHOR_NAME
                author-email: $AUTHOR_EMAIL
                author-phone: $AUTHOR_PHONE
                supplier-name: $SUPPLIER_NAME
                supplier-url: $SUPPLIER_URL
                supplier-email: $SUPPLIER_EMAIL 
                supplier-phone: $SUPPLIER_PHONE

        - name: Generate SLSA provenance statement
          id: valint_slsa_statement
          uses: scribe-security/action-bom@master
          with:
                # target: 'docker:${{ github.repository }}:${{ github.sha }}'
                type: docker
                target: my-image:latest
                format: attest-slsa
                # product-key: "slsa_attest"
                # scribe-client-id: ${{ secrets.SCRIBE_DEV_NEW_CLIENT_ID }}
                # scribe-client-secret: ${{ secrets.SCRIBE_DEV_NEW_CLIENT_SECRET }}
                # scribe-url: ${{ env.SCRIBE_URL }}
                # scribe-login-url: ${{ env.SCRIBE_LOGIN_URL }}
                # scribe-audience: ${{ env.SCRIBE_AUDIENCE }}
                

        - uses: actions/upload-artifact@v3
          with:
                name: provenance
                path: ${{ steps.valint_slsa_statement.outputs.OUTPUT_PATH }}
        
