name: stg_x509-env

on: 
  workflow_dispatch:
  # push:

env:
        LOGICAL_APP_NAME: demo-project # The app name all these SBOMs will be assosiated with
        APP_VERSION: 1.0.1 # The app version all these SBOMs will be assosiated with
        # SBOM Author meta data - Optional
        AUTHOR_NAME: Alona Dodukh
        AUTHOR_EMAIL: alonadodukh@tetsemail.com
        AUTHOR_PHONE: 123-123-123-12345
        # SBOM Supplier meta data - Optional
        SUPPLIER_NAME: Scribe-Security 
        SUPPLIER_URL: www.scribesecurity.com 
        SUPPLIER_EMAIL: info@scribesecurity.com
        SUPPLIER_PHONE: 001-001-0011
        SCRIBE_URL: "https://airflow.staging.scribesecurity.com/"
        SCRIBE_LOGIN_URL: "https://scribe-hub-staging.us.auth0.com"
        SCRIBE_AUDIENCE: "api.staging.scribesecurity.com"

jobs:

 build:
    runs-on: ubuntu-latest

    permissions:
        contents: read
        packages: write
        id-token: write

    steps:
        - uses: actions/checkout@v3

        - name: Sign Git using x509 keys
          uses: scribe-security/action-bom@master
          with:
                target: 'git:.'
                scribe-enable: true
                product-key: "Product_X509"
                components: packages,files,dep
                scribe-client-id: ${{ secrets.SCRIBE_STG_NEW_CLIENT_ID }}
                scribe-client-secret: ${{ secrets.SCRIBE_STG_NEW_CLIENT_SECRET }}
                format: attest
                attest-default: x509-env
                scribe-url: ${{ env.SCRIBE_URL }}
                scribe-login-url: ${{ env.SCRIBE_LOGIN_URL }}
                scribe-audience: ${{ env.SCRIBE_AUDIENCE }}
                product-version: "stg_pass1_x509"
          env:
            ATTEST_KEY: ${{ secrets.ATTEST_KEY_EX }}
            ATTEST_CERT: ${{ secrets.ATTEST_CERT_EX }}
            ATTEST_CA:  ${{ secrets.ATTEST_CA_EX }}

        - name: Build the Docker image
          # run: docker build . -t ${{ github.repository }}:${{ github.sha }}
          run: |
            docker build -t my-image:latest .
        # valint bom busybox:latest -o attest --attest.default=x509 --ca <my_ca.pem> --key <my_key.pem> --cert <my_cert.pem>
        - name: Sign Image using x509 keys
          uses: scribe-security/action-bom@master
          with:
                target: my-image:latest
                scribe-enable: true
                product-key: "Product_X509"
                components: packages,files,dep
                scribe-client-id: ${{ secrets.SCRIBE_STG_NEW_CLIENT_ID }}
                scribe-client-secret: ${{ secrets.SCRIBE_STG_NEW_CLIENT_SECRET }}
                format: attest
                attest-default: x509-env
                scribe-url: ${{ env.SCRIBE_URL }}
                scribe-login-url: ${{ env.SCRIBE_LOGIN_URL }}
                scribe-audience: ${{ env.SCRIBE_AUDIENCE }}
                product-version: "stg_pass1_x509"
          env:
            ATTEST_KEY: ${{ secrets.ATTEST_KEY_EX }}
            ATTEST_CERT: ${{ secrets.ATTEST_CERT_EX }}
            ATTEST_CA:  ${{ secrets.ATTEST_CA_EX }}
        
        # # valint verify busybox:latest -i attest --attest.default=x509 --ca <my_ca.pem>
        # - name: Verify Image using x509 keys
        #   uses: scribe-security/action-verify@master
        #   with:
        #         target: my-image:latest
        #         scribe-enable: true
        #         product-key: "Product_X509"
        #         components: packages,files,dep
        #         scribe-client-id: ${{ secrets.SCRIBE_STG_NEW_CLIENT_ID }}
        #         scribe-client-secret: ${{ secrets.SCRIBE_STG_NEW_CLIENT_SECRET }}
        #         input-format: attest
        #         attest-default: x509-env
        #         scribe-url: ${{ env.SCRIBE_URL }}
        #         scribe-login-url: ${{ env.SCRIBE_LOGIN_URL }}
        #         scribe-audience: ${{ env.SCRIBE_AUDIENCE }}
        #         product-version: "stg_n_x509"
        #   env:
        #     ATTEST_CA: ${{ secrets.ATTEST_CA }}
        #     ATTEST_CERT: ${{ secrets.ATTEST_CERT }}


        - name: Generate SLSA provenance statement
          id: valint_slsa_statement
          uses: scribe-security/action-bom@master
          with:
                # target: 'docker:${{ github.repository }}:${{ github.sha }}'
                type: docker
                target: my-image:latest
                format: attest-slsa
                attest-default: x509-env
                product-key: "Product_X509"
                scribe-client-id: ${{ secrets.SCRIBE_STG_NEW_CLIENT_ID }}
                scribe-client-secret: ${{ secrets.SCRIBE_STG_NEW_CLIENT_SECRET }}
                scribe-url: ${{ env.SCRIBE_URL }}
                scribe-login-url: ${{ env.SCRIBE_LOGIN_URL }}
                scribe-audience: ${{ env.SCRIBE_AUDIENCE }}
                product-version: "stg_pass1_x509"
                # ca: ${{ secrets.ATTEST_CA_EX }}
                # cert: ${{ secrets.ATTEST_CERT_EX}}
                # key: ${{ secrets.ATTEST_KEY_EX }}
                force: true
                
          env:
            ATTEST_KEY: ${{ secrets.ATTEST_KEY_EX }}
            ATTEST_CERT: ${{ secrets.ATTEST_CERT_EX }}
            ATTEST_CA:  ${{ secrets.ATTEST_CA_EX }}
  

        - uses: actions/upload-artifact@v3
          with:
                name: provenance
                path: ${{ steps.valint_slsa_statement.outputs.OUTPUT_PATH }}
        
